import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import {
  faLanguage, 
  faBars, 
  faChevronCircleLeft, 
  faChevronCircleRight, 
  faPlusCircle, 
  faImage, 
  faAlignJustify, 
  faAlignLeft,
  faAlignRight,
  faAlignCenter,
  faHome, 
  faQuestion, 
  faQuestionCircle, 
  faBlog, 
  faPhotoVideo, 
  faCamera, 
  faImages, 
  faIdCard, 
  faPhone, 
  faEnvelope,
  faPencilAlt,
  faUpload, 
  faColumns,
  faClone,
  faTrashAlt,
  faBahai,
  faTimesCircle,
  faMehBlank,
  } from '@fortawesome/free-solid-svg-icons';

  library.add(  
    faLanguage, 
    faBars, 
    faChevronCircleLeft, 
    faChevronCircleRight, 
    faPlusCircle, 
    faImage, 
    faAlignJustify, 
    faAlignLeft,
    faAlignRight,
    faAlignCenter,
    faHome, 
    faQuestion, 
    faQuestionCircle, 
    faBlog, 
    faPhotoVideo, 
    faCamera, 
    faImages, 
    faIdCard, 
    faPhone, 
    faEnvelope,
    faPencilAlt,
    faUpload, 
    faColumns,
    faClone,
    faTrashAlt,
    faBahai,
    faTimesCircle,
    faMehBlank,
    );

    export {
      library,
      FontAwesomeIcon
    }